services:
  traefik:
    image: traefik:v3.7.13
    restart: unless-stopped

    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - traefik

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped

    environment:
      PING: 1
      VERSION: 1
      BUILD: 1
      IMAGES: 1
      CONTAINERS: 1
      NETWORKS: 1
      POST: 1
      DELETE: 1

      TIMEOUT_CLIENT: 1h
      TIMEOUT_CONNECT: 10s
      TIMEOUT_SERVER: 1h

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:2375/_ping"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s


  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped

    command: redis-server --protected-mode no

    volumes:
      - redis-data:/data


  relay:
    image: ghcr.io/sergiors/relay:latest
    container_name: relay
    restart: unless-stopped

    depends_on:
      socket-proxy:
        condition: service_healthy

    environment:
      REDIS_URI: redis:6379
      REDIS_STREAM: events
      REDIS_GROUP: archivum
      LOG_LEVEL: DEBUG
      DOCKER_HOST: tcp://socket-proxy:2375
      TRAEFIK_NETWORK: traefik
      TRAEFIK_HOST_OVERRIDE: localhost

    healthcheck:
      test: ["CMD", "relay", "health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

    volumes:
      - ./functions:/functions:ro
      - relay-data:/var/lib/relay

volumes:
  redis-data:
  relay-data:

networks:
  traefik:
    name: traefik
